# cmake/utils/help.cmake
# This script is executed by the 'make help' target to display a helpful usage message.

message("")
message("Usage: make [TARGET] [VAR=VALUE]...")
message("")
message("Description:")
message("  Modern Makefile for the project, providing a streamlined, cross-platform")
message("  development workflow using CMake.")
message("")
message("Current Configuration:")
message("  BUILD_TYPE   = ${BUILD_TYPE}")
message("  BUILD_GUI    = ${BUILD_GUI}")
message("  STATIC_BUILD = ${STATIC_BUILD}")
message("  BUILD_TESTS  = ${BUILD_TESTS}")
message("  TESTNET      = ${TESTNET}")
message("  DISABLE_TOR  = ${DISABLE_TOR}")
message("")
message("Primary Targets:")
message("  help          Display this help message.")
message("  dev-build     Clean artifacts, configure, and build. Recommended for development.")
message("  build         Build the project using the existing configuration.")
message("  configure     Configure the project with the specified options.")
message("  clean         DANGEROUS: Deletes the entire build directory, including SDKs.")
message("  clean-dev     Clean build artifacts but preserve the cached SDK.")
message("")
message("Compatibility Targets:")
message("  all           Build the project for release (same as 'release').")
message("  release       Configure and build a release version.")
message("  debug         Configure and build a debug version.")
message("  gui           Build a release version with GUI.")
message("  gui-debug     Build a debug version with GUI.")
message("  static        Build a static release version.")
message("  gui-static    Build a static release version with GUI.")
message("")
message("Testing Targets:")
message("  test          Run tests on the most recently built configuration.")
message("  test-release  Build a release version with tests enabled and run them.")
message("  test-debug    Build a debug version with tests enabled and run them.")
message("")
message("Utility Targets:")
message("  build-sdk     Build bundled dependencies like Boost if required.")
message("  package-boost Package the pre-built Boost library into a distributable archive.")
message("  tags          Generate ctags for source code navigation.")
message("")
message("Examples:")
message("  make dev-build                      # Build with default settings (Release, no GUI).")
message("  make dev-build BUILD_TYPE=Debug     # Build a debug version.")
message("  make gui BUILD_TYPE=Debug           # Build a debug version with the GUI.")
message("  make test-debug                     # Build and run tests in debug mode.")
message("  make clean                          # Completely wipe the build directory.")
message("")