name: Pull Request Check

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'

jobs:
  build-linux-cli:
    uses: ./.github/workflows/testnet-cli-linux.yml
    secrets: inherit
  build-macos-arm64-cli:
    uses: ./.github/workflows/testnet-cli-macos-arm64.yml
    secrets: inherit
  build-macos-intel-cli:
    uses: ./.github/workflows/testnet-cli-macos-intel.yml
    secrets: inherit
  build-windows-cli:
    uses: ./.github/workflows/testnet-cli-windows.yml
    secrets: inherit
  build-linux-gui:
    uses: ./.github/workflows/testnet-gui-linux.yml
    secrets: inherit
  build-macos-arm64-gui:
    uses: ./.github/workflows/testnet-gui-macos-arm64.yml
    secrets: inherit
  build-macos-intel-gui:
    uses: ./.github/workflows/testnet-gui-macos-intel.yml
    secrets: inherit
  build-windows-gui:
    uses: ./.github/workflows/testnet-gui-windows.yml
    secrets: inherit