name: Pull Request Check

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  build-linux:
    name: Compile
    uses: ./.github/workflows/build-linux.yml
    with:
      chain-network: 'testnet'
      build-cli: true
      build-gui: true
    secrets: inherit
  build-windows:
    name: Compile
    uses: ./.github/workflows/build-windows.yml
    with:
      chain-network: 'testnet'
      build-cli: true
      build-gui: true
    secrets: inherit

  build-macos-arm64:
    name: Compile
    uses: ./.github/workflows/build-macos-arm64.yml
    with:
      chain-network: 'testnet'
      build-cli: true
      build-gui: true
    secrets: inherit

  build-macos-intel:
    name: Compile
    uses: ./.github/workflows/build-macos-intel.yml
    with:
      chain-network: 'testnet'
      build-cli: true
      build-gui: true
    secrets: inherit

