name: Pull Request Check

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'

jobs:
  build-windows-gui:
    uses: .github/workflows/testnet-gui-windows.yml@${{ github.ref }}
    secrets: inherit