name: PR Fast Check

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-macos-arm64:
    name: Compile
    uses: ./.github/workflows/build-macos-arm64.yml
    with:
      chain-network: ${{ env.CHAIN_NETWORK }}
      build-cli: true
      build-gui: false