name: PR Fast Check

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - dev
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CHAIN_NETWORK: ${{ github.ref_name == 'main' && 'mainnet' || 'testnet' }}

jobs:
  build-macos-arm64:
    name: Check
    uses: ./.github/workflows/build-macos-arm64.yml
    with:
      chain-network: $CHAIN_NETWORK
      build-cli: true
      build-gui: false
      artifacts: false
      release: true