name: build-linux

on:
  workflow_call:
    inputs:
      chain-network:
        description: "The network to use, can either be testnet, stagenet or mainnet"
        default: testnet
        required: false
        type: string
      build-cli:
        description: "Should the CLI be built"
        default: true
        required: false
        type: boolean
      release:
        description: "Make a release"
        default: true
        required: false
        type: boolean

jobs:
  build:
    name: Linux
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: install dependencies
        run: sudo apt-get install -y autotools-dev libicu-dev libbz2-dev git screen checkinstall zlib1g-dev miniupnpc build-essential g++ curl cmake libssl-dev bzip2

      - name: Install boost
        uses: MarkusJx/install-boost@6d8df42f57de83c5b326b5b83e7b35d650030103
        id: install-boost
        with:
          boost_version: 1.88.0
          boost_install_dir: ${{ github.workspace }}/build/boost_1_86_0
          platform_version: 24.04
          toolset: gcc
          arch: x86

      - name: Build CLI
        if: ${{ inputs.build-cli }}
        uses: ./.github/actions/cmake-build
        with:
          jobs: '4'
          build-type: 'Release'
          chain-network: ${{ inputs.chain-network }}
          boost-root: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          target: 'daemon simplewallet'
          static: 'true'
          arch: 'x86-64'
          system-deps: true

      - name: CLI Artifacts
        if: ${{ inputs.build-cli }}
        uses: ./.github/actions/sign-and-upload-release
        with:
          chain-network: ${{ inputs.chain-network }}
          release-tag: ${{ github.ref_name }}
          release: "${{ inputs.release }}"
          assets: |
            zanod
            simplewallet
          asset-type: 'cli'
          asset-directory: ${{ github.workspace }}/build/release-static/src
