name: build-macos-arm64
permissions:
  contents: write
on:
  workflow_call:
    inputs:
      chain-network:
        description: "The network to use, can either be testnet, stagenet or mainnet"
        default: testnet
        required: false
        type: string
      build-cli:
        description: "Should the CLI be built"
        default: true
        required: false
        type: boolean
      release:
        description: "Make a release"
        default: true
        required: false
        type: boolean
      release-tag:
        required: false
        type: string
        description: 'The tag for the release'

jobs:
  build-cli:
    name: MacOS Arm64
    runs-on: macos-15
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install miniupnpc

      - run: mkdir -p build/openssl
      - name: Cache OpenSSL
        id: cache-openssl
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/openssl
          key: openssl-${{ runner.os }}-${{ runner.arch }}

      - name: Build OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        run: |
          cd build
          curl -OL https://www.openssl.org/source/openssl-1.1.1w.tar.gz
          echo "cf3098950cb4d853ad95c0841f1f9c6d3dc102dccfcacd521d93925208b76ac8  openssl-1.1.1w.tar.gz" | shasum -c && tar -xjf openssl-1.1.1w.tar.gz
          rm openssl-1.1.1w.tar.gz && cd openssl-1.1.1w
          export MACOSX_DEPLOYMENT_TARGET=12.0
          ./config --prefix=${{ github.workspace }}/build/openssl --openssldir=${{ github.workspace }}/build/openssl shared zlib
          make -j3 && make install_sw install_ssldirs && cd ..
          rm -rf openssl-1.1.1w/

      - name: Build CLI
        if: ${{ inputs.build-cli }}
        run: make build BUILD_TYPE=Release

      - name: CLI Artifacts
        if: ${{ inputs.build-cli }}
        uses: ./.github/actions/sign-and-upload-release
        with:
          chain-network: ${{ inputs.chain-network }}
          release-tag: ${{ github.ref_name }}
          release: "${{ inputs.release }}"
          assets: |
            zanod
            simplewallet
          asset-type: 'cli'
          asset-directory: ${{ github.workspace }}/build/release/src
