name: build-windows

on:
  workflow_call:
    inputs:
      chain-network:
        description: "The network to use, can either be testnet, stagenet or mainnet"
        default: testnet
        required: false
        type: string
      build-cli:
        description: "Should the CLI be built"
        default: true
        required: false
        type: boolean
      build-gui:
        description: "Should the GUI be built"
        default: false
        required: false
        type: boolean
      release:
        description: "Make a release"
        default: false
        required: false
        type: boolean

jobs:
  build-cli:
    if: ${{ inputs.build-cli }}
    name: Windows CLI
    runs-on: windows-2022
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Eat the Choco
        run: |
          choco install ccache -y
          choco install zip -y

      - name: ccache caching
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/ccache
          key: ccache-${{ inputs.chain-network }}-cli-${{ runner.os }}

      - name: Install boost
        uses: MarkusJx/install-boost@6d8df42f57de83c5b326b5b83e7b35d650030103
        id: install-boost
        with:
          boost_version: 1.84.0
          boost_install_dir: ${{ github.workspace }}/build/boost_1_84_0
          platform_version: 2022
          toolset: msvc

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          CCACHE_TEMPDIR: ${{ github.workspace }}/build/ccache
        with:
          build-dir: build/release
          generator: Visual Studio 17 2022
          build-args: |
            -j4
            --config Release
          options: |
            STATIC=FALSE
            TESTNET=${{ inputs.chain-network == 'testnet'}}
            ARCH=x86-64
            CMAKE_BUILD_TYPE=Release
            Boost_INCLUDE_DIR=${{steps.install-boost.outputs.BOOST_ROOT}}/include
            Boost_LIBRARY_DIRS=${{steps.install-boost.outputs.BOOST_ROOT}}/lib

      - name: Handle Artifacts
        uses: ./.github/actions/sign-and-upload-release
        with:
          chain-network: ${{ inputs.chain-network }}
          release-tag: ${{ github.ref_name }}
          release: "${{ inputs.release }}"
          assets: |
            zanod.exe
            simplewallet.exe
            connectivity_tool.exe
          asset-type: 'cli'
          asset-directory: ${{ github.workspace }}\build\release\src\Release

  build-gui:
    if: ${{ inputs.build-gui }}
    name: Windows GUI
    runs-on: windows-2022
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Eat the Choco
        run: |
          choco install ccache -y
          choco install zip -y

      - name: ccache caching
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/ccache
          key: ccache-${{ inputs.chain-network }}-gui-${{ runner.os }}

      - name: Install boost
        uses: MarkusJx/install-boost@6d8df42f57de83c5b326b5b83e7b35d650030103
        id: install-boost
        with:
          boost_version: 1.84.0
          boost_install_dir: ${{ github.workspace }}/build/boost_1_84_0
          platform_version: 2022
          toolset: msvc

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: '${{ github.workspace }}/build/qt/'
          aqtversion: '==3.1.*'
          version: '6.8.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'qt5compat qtwebengine qtwebchannel qtpositioning'


      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          CCACHE_TEMPDIR: ${{ github.workspace }}/build/ccache
        with:
          build-dir: build/release
          generator: Visual Studio 17 2022
          build-args: |
            -j4
            --config Release
          options: |
            STATIC=FALSE
            TESTNET=${{ inputs.chain-network == 'testnet'}}
            ARCH=x86-64
            CMAKE_BUILD_TYPE=Release
            BUILD_GUI=1
            Boost_INCLUDE_DIR=${{steps.install-boost.outputs.BOOST_ROOT}}/include
            Boost_LIBRARY_DIRS=${{steps.install-boost.outputs.BOOST_ROOT}}/lib

      - name: Handle Artifacts
        uses: ./.github/actions/sign-and-upload-release
        with:
          chain-network: ${{ inputs.chain-network }}
          release-tag: ${{ github.ref_name }}
          release: "${{ inputs.release }}"
          assets: |
            Zano.exe
          asset-type: 'gui'
          asset-directory: ${{ github.workspace }}\build\release\src\Release
