name: build-windows

on:
  workflow_call:
    inputs:
      chain-network:
        description: "The network to use, can either be testnet, stagenet or mainnet"
        default: testnet
        required: false
        type: string
      build-cli:
        description: "Should the CLI be built"
        default: true
        required: false
        type: boolean
      release:
        description: "Make a release"
        default: true
        required: false
        type: boolean

jobs:
  build:
    name: Windows
    runs-on: windows-2022
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14

      - name: Install Perl CPAN modules
        shell: powershell
        run: |
          choco install -y boost-msvc-14.3
          choco install -y openssl

      - name: Build CLI
        if: ${{ inputs.build-cli }}
        shell: pwsh
        run: |
          make.exe configure BUILD_TYPE=Release CMAKE_GENERATOR="Visual Studio 17 2022" OPENSSL_USE_SYSTEM=ON
          make.exe build_sdk BUILD_TYPE=Release CMAKE_GENERATOR="Visual Studio 17 2022" OPENSSL_USE_SYSTEM=ON
          make.exe build BUILD_TYPE=Release CMAKE_GENERATOR="Visual Studio 17 2022" OPENSSL_USE_SYSTEM=ON

      - name: CLI Artifacts
        if: ${{ inputs.build-cli }}
        uses: ./.github/actions/sign-and-upload-release
        with:
          chain-network: ${{ inputs.chain-network }}
          release-tag: ${{ github.ref_name }}
          release: "${{ inputs.release }}"
          assets: |
            zanod.exe
            simplewallet.exe
            connectivity_tool.exe
          asset-type: 'cli'
          asset-directory: ${{ github.workspace }}\build\release\src\Release
