name: build-linux

on:
  workflow_call:
    inputs:
      chain-network:
        description: "The network to use, can either be testnet, stagenet or mainnet"
        default: testnet
        required: false
        type: string
      build-cli:
        description: "Should the CLI be built"
        default: true
        required: false
        type: boolean
      build-gui:
        description: "Should the GUI be built"
        default: true
        required: false
        type: boolean
      release:
        description: "Make a release"
        default: true
        required: false
        type: boolean

jobs:
  build:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: install dependencies
        run: sudo apt-get install -y autotools-dev libicu-dev libbz2-dev git screen checkinstall zlib1g-dev ccache miniupnpc build-essential g++ curl cmake libssl-dev bzip2
      - name: ccache caching
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/ccache
          key: ccache-${{ inputs.chain-network }}-${{ runner.os }}

      - name: Install Qt
        if: ${{ inputs.build-gui }}
        uses: jurplel/install-qt-action@v3
        with:
          dir: '${{ github.workspace }}/build/qt/'
          aqtversion: '==3.1.*'
          version: '6.8.3'
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
          modules: 'qt5compat qtwebengine qtwebchannel qtpositioning'

      - name: Build SDK via Makefile
        run: make build_sdk BUILD_TYPE=Release STATIC_BUILD=ON

      - name: Build CLI
        if: ${{ inputs.build-cli }}
        run: make build BUILD_TYPE=Release STATIC_BUILD=ON TARGETS="daemon simplewallet connectivity_tool"

      - name: CLI Artifacts
        if: ${{ inputs.build-cli }}
        uses: ./.github/actions/sign-and-upload-release
        with:
          chain-network: ${{ inputs.chain-network }}
          release-tag: ${{ github.ref_name }}
          release: "${{ inputs.release }}"
          assets: |
            zanod
            simplewallet
            connectivity_tool
          asset-type: 'cli'
          asset-directory: ${{ github.workspace }}/build/release/src

      - name: Build GUI
        if: ${{ inputs.build-gui }}
        run: make build BUILD_TYPE=Release STATIC_BUILD=ON BUILD_GUI=ON TARGETS="Zano"

      - name: GUI Artifacts
        if: ${{ inputs.build-gui }}
        uses: ./.github/actions/sign-and-upload-release
        with:
          chain-network: ${{ inputs.chain-network }}
          release-tag: ${{ github.ref_name }}
          release: "${{ inputs.release }}"
          assets: |
            Zano
          asset-type: 'gui'
          asset-directory: ${{ github.workspace }}/build/release/src