name: Build All Pre-built Dependencies

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

jobs:
  build-matrix:
    name: Build Boost v${{ matrix.boost_version }} on Ubuntu 24.04
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false # Allow other jobs to continue if one version fails
      matrix:
        boost_version:
          - '1.80.0'
          - '1.81.0'
          - '1.82.0'
          - '1.83.0'
          - '1.84.0'
          - '1.85.0'
          - '1.86.0'
          - '1.87.0'
          - '1.88.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure the project for Boost v${{ matrix.boost_version }}
        run: make configure BUILD_TYPE=Release BOOST_VERSION=${{ matrix.boost_version }}

      - name: Build the Boost SDK
        run: make build_sdk

      - name: Package the Boost SDK
        run: make package-boost

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          # Use a consistent name for all packages from this run
          name: boost-packages
          path: ./*.tar.gz